[features]
seeds = false
skip-lint = false
[programs.localnet]
testando_sol = "9AtepmRcorvUw7sHrHTcfABofswrkFKXzmmK2kJiMW8b"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tuzin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
